In [122]:
import numpy as np
import pandas as pd

# Total Station Lab

In [123]:
dist = np.array([284.390, 206.405, 210.402, 211.302, 96.961, 134.508])
brg = np.array([90.000, 106.89027778, 298.79222222, 292.2838889, 277.58694444, 182.52027778])
dist,brg

(array([ 284.39 ,  206.405,  210.402,  211.302,   96.961,  134.508]),
 array([  90.        ,  106.89027778,  298.79222222,  292.2838889 ,
         277.58694444,  182.52027778]))

#### Latitude and Departure

In [124]:
lat =  dist * np.cos(np.radians(brg))
dep = dist * np.sin(np.radians(brg))
np.around(lat, decimals = 3), np.around(dep, decimals = 3)

(array([   0.   ,  -59.969,  101.337,   80.125,   12.802, -134.378]),
 array([ 284.39 ,  197.501, -184.39 , -195.521,  -96.112,   -5.915]))

#### Sum Dist, LAT & DEP

In [125]:
perimeter = np.sum(dist)
sum_lat = np.sum(lat)
sum_dep = np.sum(dep)
np.around(perimeter, decimals = 3), sum_lat, sum_dep

(1143.9680000000001, -0.083179146977641949, -0.047236386849489165)

#### Adjusted LAT

In [126]:
for di in dist:
    adj_lat = sum_lat / sum_dist  * dist
    adj_lat = lat - adj_lat
    
adj_lat = pd.Series(adj_lat)
np.around(adj_lat, decimals = 3)

0      0.021
1    -59.954
2    101.352
3     80.140
4     12.809
5   -134.368
dtype: float64

#### Adjusted DEP

In [127]:
for di in dist:
    adj_dep = sum_dep / sum_dist  * dist
    adj_dep = dep - adj_dep
    
adj_dep = pd.Series(adj_dep)
np.around(adj_dep, decimals = 3)

0    284.402
1    197.510
2   -184.382
3   -195.512
4    -96.108
5     -5.909
dtype: float64

#### Adjusted Distance

In [128]:
adj_dist = np.sqrt(np.square(adj_lat) + np.square(adj_dep))
np.around(adj_dist, decimals = 3)

0    284.402
1    206.409
2    210.402
3    211.300
4     96.958
5    134.498
dtype: float64

#### Adjusted Bearing

In [153]:
x = np.degrees(np.arctan(adj_dep / adj_lat))
y = np.around(x - brg)
y = x - y
y

0     89.995834
1    106.885604
2    298.797013
3    292.288641
4    277.591387
5    182.518097
dtype: float64

#### Dataframe

In [154]:
dist = pd.Series(dist)
brg = pd.Series(brg)
lat = pd.Series(lat)
dep = pd.Series(dep)
adj_lat = pd.Series(adj_lat)
adj_dep = pd.Series(adj_dep)


In [157]:
df1 = pd.DataFrame(dist, columns = ["Distance"])
df2 = pd.DataFrame(brg, columns = ["Bearing"])
df3 = pd.DataFrame(np.around(lat, decimals = 3), columns = ["Latitude"])
df4 = pd.DataFrame( np.around(dep, decimals = 3), columns = ["Departure"])
df5 = pd.DataFrame(np.around(adj_lat, decimals = 3), columns = ["Adj. Lat."])
df6 = pd.DataFrame(np.around(adj_dep, decimals = 3), columns = ["Adj. Dep."])
df7 = pd.DataFrame(np.around(adj_dist, decimals = 3), columns = ["Adj. Dist."])
df8 = pd.DataFrame(np.around(y, decimals = 6), columns = ["Adj. Brg"])

df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8], join ="outer", axis = 1)
df

Distance     Bearing  Latitude  Departure  Adj. Lat.  Adj. Dep.  \
0   284.390   90.000000     0.000    284.390      0.021    284.402   
1   206.405  106.890278   -59.969    197.501    -59.954    197.510   
2   210.402  298.792222   101.337   -184.390    101.352   -184.382   
3   211.302  292.283889    80.125   -195.521     80.140   -195.512   
4    96.961  277.586944    12.802    -96.112     12.809    -96.108   
5   134.508  182.520278  -134.378     -5.915   -134.368     -5.909   

   Adj. Dist.    Adj. Brg  
0     284.402   89.995834  
1     206.409  106.885604  
2     210.402  298.797013  
3     211.300  292.288641  
4      96.958  277.591387  
5     134.498  182.518097